config/routes.rb
Rails.application.routes.draw do
  # Retrieve HTML pages
  constraints(format: 'html') do
    devise_for :users
    resources :users
    resources :pages
  end

  root 'pages#home'

  # Retrieve JSON data
  constraints(format: 'json') do
  end

  # Retrieve PDF table
  constraints(format: 'pdf') do
  end
end

app/models/abilities/everyone.rb
module Abilities
  class Everyone
    include CanCan::Ability

    def initialize(user)
      can [:home], :page
    end
  end
end

app/models/ability.rb
class Ability
  include CanCan::Ability

  def initialize(user)
    user ||= User.new

    merge Abilities::Everyone.new(user)

#    if !user.new_record?
#      merge Abilities::Authenticated.new(user)
#      merge Abilities::Admin.new(user) if user.admin?
#    else
#      merge Abilities::Guest.new(user)
#    end
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/page.rb
class Page < ApplicationRecord
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  check_authorization :unless => :devise_controller?
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  before_action :set_page, only: [:show, :edit, :update, :destroy]

  authorize_resource :class => false

  def home
  end

  # GET /pages
  def index
    @pages = Page.all
  end

  # GET /pages/1
  def show
  end

  # GET /pages/new
  def new
    @page = Page.new
  end

  # GET /pages/1/edit
  def edit
  end

  # POST /pages
  def create
    @page = Page.new(page_params)

    respond_to do |format|
      if @page.save
        format.html { redirect_to @page, notice: 'Page was successfully created.' }
      else
        format.html { render :new }
      end
    end
  end

  # PATCH/PUT /pages/1
  def update
    respond_to do |format|
      if @page.update(page_params)
        format.html { redirect_to @page, notice: 'Page was successfully updated.' }
      else
        format.html { render :edit }
      end
    end
  end

  # DELETE /pages/1
  def destroy
    @page.destroy
    respond_to do |format|
      format.html { redirect_to pages_url, notice: 'Page was successfully destroyed.' }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_page
      @page = Page.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def page_params
      params.fetch(:page, {})
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show, :edit, :update, :destroy]

  # GET /users
  def index
    @users = User.all
  end

  # GET /users/1
  def show
  end

  # GET /users/new
  def new
    @user = User.new
  end

  # GET /users/1/edit
  def edit
  end

  # POST /users
  def create
    @user = User.new(user_params)

    respond_to do |format|
      if @user.save
        format.html { redirect_to @user, notice: 'User was successfully created.' }
      else
        format.html { render :new }
      end
    end
  end

  # PATCH/PUT /users/1
  def update
    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to @user, notice: 'User was successfully updated.' }
      else
        format.html { render :edit }
      end
    end
  end

  # DELETE /users/1
  def destroy
    @user.destroy
    respond_to do |format|
      format.html { redirect_to users_url, notice: 'User was successfully destroyed.' }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = User.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def user_params
      params.fetch(:user, {})
    end
end

app/helpers/application_helper.rb
module ApplicationHelper

end

app/helpers/icon_helper.rb
module IconHelper
  def kIcon(symbol, options = {})
    return "" if symbol.nil?

    icon = Octicons::Octicon.new(symbol, options)
    options[:class] = "kronos-icon"
    return content_tag(:svg, icon.path.gsub("/>", '></path>').html_safe, icon.options)
  end
end

app/views/layouts/_footer.html.haml
%footer.kronos-footer
  .row
    .col-sm-3.col-lg-2.text-center
      %a{:href => "#"} Red Drop Design
    .col-sm-3.col-lg-2.text-center
      %a{:href => "#"} Sportkoepel UT
    .col-sm-3.col-lg-2.text-center
      %a{:href => "#"} Glaszetter in Enschede nodig?
    .col-sm-3.col-lg-2.text-center
      %a{:href => "#"} Goodkoop verhuizen? Verhuizen.com
    .col-lg-4
      %address
        %b Drienerlose Atletiek Vereniging Kronos
        %br
        Postbus 217
        %br
        7500 AE  Enschede
        %br
        %a{:href => "mailto:info@kronos.nl"} info@kronos.nl

app/views/layouts/_header.html.haml
%header
  %nav.navbar.navbar-expand.kronos-navbar
    %span.mx-auto.navbar-brand
      .d-none.d-sm-none.d-md-none.d-lg-block.d-xl-block
        =image_tag "kronos_logo_large.png"
      .d-none.d-sm-none.d-md-block.d-lg-none.d-xl-none
        =image_tag "kronos_logo_medium.png"
  %nav.navbar.navbar-expand-lg.kronos-navbar
    %a.navbar-brand.nav-link{:href => "#"}
      .d-none.d-sm-none.d-md-none.d-lg-block.d-xl-block
        Home
      .d-block.d-sm-block.d-md-block.d-lg-none.d-xl-none
        Kronos
    %button.navbar-toggler{:type => "button", "data-toggle" => "collapse", "data-target" => "#navbarNav", "aria-expanded" => "false", "aria-label" => "Toggle naviation"}
      =kIcon "three-bars", :class => "kronos-icon-white"
    #navbarNav.collapse.navbar-collapse
      %ul.navbar-nav
        %li.nav-item
          %a.nav-link{:href => "#"}
            Vereniging
            =kIcon "triangle-down"
        %li.nav-item
          %a.nav-link{:href => "#"}
            Trainingen
            =kIcon "triangle-down"
        %li.nav-item
          %a.nav-link{:href => "#"}
            Wedstrijden
            =kIcon "triangle-down"
        %li.nav-item
          %a.nav-link{:href => "#"}
            Agenda
        %li.nav-item
          %a.nav-link{:href => "#"}
            Uitslagen
        %li.nav-item
          %a.nav-link{:href => "#"}
            Foto's
        %li.nav-item
          %a.nav-link{:href => "#"}
            Contact
    %ul.navbar-nav.ml-auto
      %li.nav-item
        %a.nav-link{:href => "#"}
          Log in
          =kIcon "triangle-down"

app/views/layouts/application.html.haml
!!! 5
%html{:lang => "en"}
  %head
    %meta{:charset => "utf-8"}
    %meta{:name => "viewport", :content => "width=device-width, initial-scale=1, shrink-to-fit=no"}
    %title Kronos
    = csrf_meta_tags
    = favicon_link_tag       'favicon.ico'
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload'
    %link{:href => "//fonts.googleapis.com/css?family=Droid+Serif:400,700,700italic,400italic|Roboto", :rel => "stylesheet", :type => "text/css"}
    = javascript_include_tag 'application', 'data-turbolinks-track': 'reload'
  %body
    .container
      = render 'layouts/header'
      = yield
      = render 'layouts/footer'

app/views/pages/_form.html.haml
= form_with(model: page, local: true) do |form|
  - if page.errors.any?
    #error_explanation
      %h2
        = pluralize(page.errors.count, "error")
        prohibited this page from being saved:
      %ul
        - page.errors.full_messages.each do |message|
          %li= message
  .actions
    = form.submit

app/views/pages/edit.html.haml
%h1 Editing Page
= render 'form', page: @page
= link_to 'Show', @page
|
= link_to 'Back', pages_path

app/views/pages/home.html.haml
%p Hallo

app/views/pages/index.html.haml
%p#notice= notice
%h1 Pages
%table
  %thead
    %tr
      %th{:colspan => "3"}
  %tbody
    - @pages.each do |page|
      %tr
        %td= link_to 'Show', page
        %td= link_to 'Edit', edit_page_path(page)
        %td= link_to 'Destroy', page, method: :delete, data: { confirm: 'Are you sure?' }
%br/
= link_to 'New Page', new_page_path

app/views/pages/new.html.haml
%h1 New Page
= render 'form', page: @page
= link_to 'Back', pages_path

app/views/pages/show.html.haml
%p#notice= notice
= link_to 'Edit', edit_page_path(@page)
|
= link_to 'Back', pages_path

app/views/users/_form.html.haml
= form_with(model: user, local: true) do |form|
  - if user.errors.any?
    #error_explanation
      %h2
        = pluralize(user.errors.count, "error")
        prohibited this user from being saved:
      %ul
        - user.errors.full_messages.each do |message|
          %li= message
  .actions
    = form.submit

app/views/users/edit.html.haml
%h1 Editing User
= render 'form', user: @user
= link_to 'Show', @user
|
= link_to 'Back', users_path

app/views/users/index.html.haml
%p#notice= notice
%h1 Users
%table
  %thead
    %tr
      %th{:colspan => "3"}
  %tbody
    - @users.each do |user|
      %tr
        %td= link_to 'Show', user
        %td= link_to 'Edit', edit_user_path(user)
        %td= link_to 'Destroy', user, method: :delete, data: { confirm: 'Are you sure?' }
%br/
= link_to 'New User', new_user_path

app/views/users/new.html.haml
%h1 New User
= render 'form', user: @user
= link_to 'Back', users_path

app/views/users/show.html.haml
%p#notice= notice
= link_to 'Edit', edit_user_path(@user)
|
= link_to 'Back', users_path